# permissions for end users to view inttesthelpers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inttesthelper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nnf-integration-test-operator
    app.kubernetes.io/part-of: nnf-integration-test-operator
    app.kubernetes.io/managed-by: kustomize
  name: inttesthelper-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - inttesthelpers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - inttesthelpers/status
  verbs:
  - get
