# permissions for end users to view inttestmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inttestmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nnf-integration-test-operator
    app.kubernetes.io/part-of: nnf-integration-test-operator
    app.kubernetes.io/managed-by: kustomize
  name: inttestmanager-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - inttestmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - inttestmanagers/status
  verbs:
  - get
